---
- hosts: all

  pre_tasks:

    - name: Install rsyslog
      yum:
        name: rsyslog
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install rsyslog
      apt:
        name:
        - curl
        - rsyslog
        state: present
      when: ansible_os_family == 'Debian'

  roles:
    - role: ansible-role-haproxy
      haproxy_syslog_enable: True
      haproxy_syslog_configure_udp: True
      haproxy_frontends:
        - name: hafrontend-http
          address: '*:80'
          backend: habackend
        - name: hafrontend-tcp
          address: '*:81'
          mode: tcp
          backend: habackend
      haproxy_backends:
        - name: habackend
          mode: http
          servers:
            - name: app1
              address: 192.168.0.1:80
            - name: app2
              address: 192.168.0.2:80

  # pre_tasks:
  #   - name: Update apt cache.
  #     apt: update_cache=yes cache_valid_time=600
  #     when: ansible_os_family == 'Debian'
