---
- block:
  - name: Enable Backports repository (Debian).
    ansible.builtin.deb822_repository:
      name: "{{ ansible_facts['distribution_release'] }}-backports"
      types: deb
      uris: "http://ftp.debian.org/debian"
      suites: "{{ ansible_facts['distribution_release'] }}-backports"
      components: main
      state: present

  - name: Update the repository cache and update package default release backport
    apt:
      name: "{{ haproxy_package_name }}"
      state: latest
      default_release: "{{ ansible_facts['distribution_release'] }}-backports"
      update_cache: yes
    when: ansible_facts['distribution'] == "Debian" and haproxy_use_backports
  when: ansible_facts['distribution'] == "Debian" and haproxy_use_backports | bool


- name: install | add repository from PPA and install its signing key
  apt_repository:
    repo: "{{ haproxy_ppa }}"
    update_cache: true
  when: haproxy_use_ppa
  tags:
    - haproxy-install-add-repository

- name: install | dependencies
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - haproxy-install-dependencies


- name: install | additional
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ haproxy_install }}"
  tags:
    - haproxy-install-additional
