---
- block:
  - name: Enable Backports repository (Debian).
    ansible.builtin.deb822_repository:
      name: "{{ ansible_facts['distribution_release'] }}-backports"
      types: deb
      uris: "http://ftp.debian.org/debian"
      suites: "{{ ansible_facts['distribution_release'] }}-backports"
      components: main
      state: present

  - name: Update the repository cache and update package default release backport
    apt:
      name: "{{ haproxy_package_name }}"
      state: latest
      default_release: "{{ ansible_facts['distribution_release'] }}-backports"
      update_cache: yes
    when: ansible_facts['distribution'] == "Debian" and haproxy_use_backports
  when: ansible_facts['distribution'] == "Debian" and haproxy_use_backports | bool


- name: install | add HAProxy PPA signing key
  ansible.builtin.get_url:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCCB6CF8783BCD2A0BE2A20C2F0448CD2E653920"
    dest: /etc/apt/keyrings/haproxy.asc
    mode: '0644'
  when: haproxy_use_ppa

- name: install | add repository from PPA
  ansible.builtin.deb822_repository:
    name: haproxy
    types: deb
    uris: "https://ppa.launchpadcontent.net/vbernat/haproxy-{{ haproxy_version }}/ubuntu"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: /etc/apt/keyrings/haproxy.asc
    state: present
  when: haproxy_use_ppa

- name: install | update apt cache after adding PPA
  ansible.builtin.apt:
    update_cache: true
  when: haproxy_use_ppa
  tags:
    - haproxy-install-add-repository

- name: install | dependencies
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - haproxy-install-dependencies


- name: install | additional
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ haproxy_install }}"
  tags:
    - haproxy-install-additional
