---

- name: Ensure the ssl certs dir exists
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
    owner: root
  with_items:
    - {
        path: "{{ haproxy_ssl_path }}",
        mode: '0750'
    }
    - {
        path: "{{ haproxy_key_path }}",
        mode: '0750'
    }

# Generate keys for use with LUA scripts
#openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out account.key
#openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out example.net.key

- name: Generate an OpenSSL private key for the account
  community.crypto.openssl_privatekey:
    path: "{{ haproxy_key_path }}/{{ haproxy_lua_accountname }}.key"
    size: 4096
    mode: 0600

- name: Generate an OpenSSL private key for the domain
  community.crypto.openssl_privatekey:
    path: "{{ haproxy_key_path }}/{{ item }}.key"
    size: 2048
    mode: 0600
  with_items: haproxy_key_domains
