---

- name: check version support
  fail:
    msg: "HAProxy version {{ haproxy_version }} is not supported"
  when: haproxy_version | string not in haproxy_versions_supported
  tags:
    - configuration
    - haproxy
    - haproxy-check-version-support

- import_tasks: install.yml
  tags:
    - configuration
    - haproxy
    - haproxy-install

- import_tasks: certificates.yml
  tags:
    - configuration
    - haproxy
    - haproxy-certificates

- import_tasks: acl.yml
  tags:
    - configuration
    - haproxy
    - haproxy-acl

- import_tasks: lua.yml
  tags:
    - configuration
    - haproxy
    - haproxy-lua

- import_tasks: configuration.yml
  tags:
    - configuration
    - haproxy
    - haproxy-configuration

- import_tasks: logging.yml
  tags:
    - configuration
    - haproxy
    - haproxy-logging


- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  become: true
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

- name: Configure SELinux to allow all connections
  become: true
  seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true
  # selinux_enabled fact is set by ome.selinux_utils
  # Since this is an external role we can't assume it's been run
  when: "selinux_enabled | default(False)"


- name: Ensure HAProxy is started and enabled on boot.
  service:
    name: haproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  become: true
  tags:
    - configuration
    - haproxy
    - haproxy-start-enable-service
